---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGJqY21hMzFsCg==
  CLOUDINARY_KEY: ODU1ODc3MTc5NDI2NTIzCg==
  CLOUDINARY_SECRET: V0dCb1JFcWJSaG5MUkhUT1ZiUW5ZUzdhbEZZCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2ljM1Z6YUdGdWRIQmhkMkZ5TWpVaUxDSmhJam9pWTJ4NWFuUnVNbkJpTURBeGN6SnNjMkpuYVhKaWNXY3laQ0o5LndYS1oyWEhXa1BFUzBVT1RXZG5OM0EK
  DB_URL: bW9uZ29kYitzcnY6Ly9weXN1c2hhbnRwYXdhcjpkM0NxUEs4Z1JmRzJKUVhxQHN1c2hhbnQtZHMudnprOG5jaC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9U3VzaGFudC1EUwo=
  SECRET: c3VzaGFudHNoYWNrCg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec: 
      containers:
        - name: yelp-camp-container
          image: sushantpawar25/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
